[toolchain]
package_manager = "yarn"
anchor_version = "0.31.0"

[features]
resolution = true
skip-lint = false

[programs.localnet]
warmkey = "warmPv4soGeXuRHdiUj6hiFRhaxFsP2h1B2aF6Gd3KF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[test]
startup_wait = 10000

[scripts]
test = "yarn run --no-cache ts-mocha -p ./tsconfig.json -t 1000000 tests/**/warmkey.ts"
test2 = "yarn run --no-cache ts-mocha -p ./tsconfig.json -t 1000000 tests/**/misc.ts"

