[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
warmkey = "FJeV4XT5gPHbDZEbLwGqoZUwdmn5Rzu91A1PstzggShg"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run --no-cache ts-mocha -p ./tsconfig.json -t 1000000 tests/**/warmkey.ts"

